'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import {
  FileSearch, Cpu, Target, Search, TrendingUp, Star, FileText, CheckCircle2,
  BrainCircuit, MessageCircle, MessageSquareCode, BarChart2, Trophy, Clock, Users, Sparkles
} from 'lucide-react';
import { MetricsSection } from '../../components/landing/MetricsSection';
import { CTASection } from '../../components/landing/CTASection';

const RESUME_FEATURES = [
  { icon: FileSearch, title: 'Resume Upload', desc: 'Drag-and-drop or click to upload PDF or DOCX files up to 10MB. Multi-format support with intelligent parsing.', badge: 'Core' },
  { icon: Cpu, title: 'AI Resume Parsing', desc: 'Our NLP engine extracts every detail from your resume — skills, experience, education, and achievements — with 99% accuracy.', badge: 'AI' },
  { icon: Target, title: 'ATS Match Analysis', desc: 'Deep comparison against any job description. Know exactly which ATS keywords you have, which you\'re missing, and your match percentage.', badge: 'Core' },
  { icon: Search, title: 'Keyword Analysis', desc: 'Complete breakdown of hard skills, soft skills, certifications, tools, and technologies extracted from both your resume and the target JD.', badge: 'AI' },
  { icon: TrendingUp, title: 'Missing Skills Detection', desc: 'Identify every skill in the job description that\'s absent from your resume, ranked by frequency and importance to recruiters.', badge: 'AI' },
  { icon: Star, title: 'Resume Score', desc: 'A composite score (0-100) based on ATS match, keyword density, formatting signals, and completeness of key resume sections.', badge: 'Core' },
  { icon: Sparkles, title: 'AI Improvements', desc: 'Line-by-line rewrite suggestions, missing bullet points to add, and better phrasing recommendations — all generated by GPT-4.', badge: 'AI' },
  { icon: FileText, title: 'PDF Report Generation', desc: 'Download a professional branded PDF with your full analysis, ATS score, keyword gaps, skill extraction, and improvement plan.', badge: 'Pro' },
  { icon: CheckCircle2, title: 'Skill Extraction', desc: 'Automatically tags and categorizes your skills into technical, soft, domain, tooling, and certification buckets for easy review.', badge: 'Core' },
];

const INTERVIEW_FEATURES = [
  { icon: Users, title: 'Role Selection', desc: 'Choose from 20+ job roles including SWE, ML Engineer, Data Scientist, Product Manager, DevOps, and more.', badge: 'Core' },
  { icon: BrainCircuit, title: 'Technical Questions', desc: 'Role-specific technical questions covering algorithms, system design, language-specific topics, and real-world problem-solving.', badge: 'AI' },
  { icon: MessageCircle, title: 'Behavioral Questions', desc: 'STAR-method behavioral questions tailored to seniority level. Covers leadership, conflict resolution, failure stories, and more.', badge: 'AI' },
  { icon: Trophy, title: 'Mock Interview Mode', desc: 'Full end-to-end mock interview with timed questions, real-time coaching, and a comprehensive debrief at the end.', badge: 'Pro' },
  { icon: Star, title: 'AI Evaluation', desc: 'Every answer is scored against a database of ideal responses from top engineers. Evaluation happens in real time.', badge: 'AI' },
  { icon: MessageCircle, title: 'Communication Score', desc: 'Scored on clarity, sentence structure, conciseness, vocabulary, and how well your answer reads to a technical recruiter.', badge: 'AI' },
  { icon: BarChart2, title: 'Technical Score', desc: 'Evaluates depth, accuracy, completeness, edge case coverage, and whether you\'d have passed a real interview on this question.', badge: 'AI' },
  { icon: Trophy, title: 'Confidence Score', desc: 'Based on assertiveness, hedging language analysis, directness, and decisiveness in your responses.', badge: 'AI' },
  { icon: Clock, title: 'Interview History', desc: 'Every session is permanently saved. Review past answers, compare scores, and see which question types you\'re weakest on.', badge: 'Pro' },
  { icon: TrendingUp, title: 'Performance Tracking', desc: 'Track your scores across sessions. Visualize your improvement with charts showing technical, communication, and confidence trends.', badge: 'Pro' },
];

const BADGE_COLORS: Record<string, string> = {
  Core: 'bg-[var(--color-canvas-line-soft)] text-[var(--color-ink-dim)] border-[var(--color-canvas-line)]',
  AI: 'bg-[var(--color-accent)]/10 text-[var(--color-accent-lighter)] border-[var(--color-accent)]/25',
  Pro: 'bg-[#F59E0B]/10 text-[#F59E0B] border-[#F59E0B]/25',
};

function FeatureGrid({ features }: { features: typeof RESUME_FEATURES }) {
  const { ref, inView } = useInView({ threshold: 0.05, triggerOnce: true });

  return (
    <div ref={ref} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {features.map(({ icon: Icon, title, desc, badge }, i) => (
        <motion.div
          key={title}
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: i * 0.04, ease: [0.22, 1, 0.36, 1] }}
          className="glass-card-hover group p-5 hover:-translate-y-1"
        >
          <div className="flex items-start justify-between mb-4">
            <div className="w-9 h-9 rounded-xl bg-[var(--color-accent)]/10 flex items-center justify-center group-hover:bg-[var(--color-accent)]/20 transition-colors">
              <Icon className="w-[18px] h-[18px] text-[var(--color-accent)]" />
            </div>
            <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded-full border ${BADGE_COLORS[badge]}`}>
              {badge}
            </span>
          </div>
          <h3 className="font-display font-semibold text-[var(--color-ink)] mb-2">{title}</h3>
          <p className="text-sm text-[var(--color-ink-dim)] leading-relaxed">{desc}</p>
        </motion.div>
      ))}
    </div>
  );
}

export function FeaturesPageClient() {
  const [activeTab, setActiveTab] = useState<'resume' | 'interview'>('resume');

  return (
    <main>
      {/* Hero */}
      <section className="relative overflow-hidden pt-36 pb-16 px-4">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[900px] h-[420px] bg-[var(--color-accent)]/8 rounded-full blur-[160px] pointer-events-none" />
        <div className="max-w-4xl mx-auto text-center relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="section-eyebrow-violet mb-4 inline-flex">
              <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-accent)]" />
              Full Feature Breakdown
            </span>
            <h1 className="text-5xl md:text-7xl font-display font-semibold tracking-tight mt-4 mb-5">
              Everything you need.<br />
              <span className="gradient-text-violet">Nothing you don&apos;t.</span>
            </h1>
            <p className="text-[var(--color-ink-dim)] text-lg max-w-2xl mx-auto leading-relaxed">
              AI Career Coach is built around two tightly integrated tools. Here&apos;s a complete breakdown of every feature in both.
            </p>
          </motion.div>
        </div>
      </section>

      <MetricsSection />

      {/* Tab switcher + feature grid */}
      <section className="py-24 px-4 border-t border-[var(--color-canvas-line-soft)] bg-[var(--color-canvas-deep)] relative overflow-hidden">
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-[var(--color-accent)]/[0.05] rounded-full blur-[180px] pointer-events-none" />
        <div className="max-w-6xl mx-auto relative">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4 }}
            className="flex items-center justify-center mb-12"
          >
            <div className="inline-flex items-center gap-1 bg-[var(--color-canvas-raise)] border border-[var(--color-canvas-line)] rounded-full p-1.5">
              <button
                onClick={() => setActiveTab('resume')}
                aria-pressed={activeTab === 'resume'}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-full text-sm font-semibold transition-all ${
                  activeTab === 'resume'
                    ? 'bg-[var(--color-accent)] text-[var(--color-ink)] shadow-[0_0_20px_rgba(var(--color-accent-rgb),0.35)]'
                    : 'text-[var(--color-ink-dim)] hover:text-[var(--color-ink)]'
                }`}
              >
                <FileSearch className="w-4 h-4" />
                AI Resume Analyzer
              </button>
              <button
                onClick={() => setActiveTab('interview')}
                aria-pressed={activeTab === 'interview'}
                className={`flex items-center gap-2 px-5 py-2.5 rounded-full text-sm font-semibold transition-all ${
                  activeTab === 'interview'
                    ? 'bg-[var(--color-accent)] text-[var(--color-ink)] shadow-[0_0_20px_rgba(var(--color-accent-rgb),0.35)]'
                    : 'text-[var(--color-ink-dim)] hover:text-[var(--color-ink)]'
                }`}
              >
                <MessageSquareCode className="w-4 h-4" />
                AI Interview Coach
              </button>
            </div>
          </motion.div>

          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
          >
            <FeatureGrid features={activeTab === 'resume' ? RESUME_FEATURES : INTERVIEW_FEATURES} />
          </motion.div>
        </div>
      </section>

      <CTASection />
    </main>
  );
}
